### PML LAB CIA-1

### REG NO-225229128

In [123]:
import pandas as pd

In [124]:
### read test file

In [129]:
d=pd.read_csv('test.csv')
print(d)

     PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0013_01      Earth      True     G/3/S    TRAPPIST-1e  27.0  False
1        0018_01      Earth     False     F/4/S    TRAPPIST-1e  19.0  False
2        0019_01     Europa      True     C/0/S    55 Cancri e  31.0  False
3        0021_01     Europa     False     C/1/S    TRAPPIST-1e  38.0  False
4        0023_01      Earth     False     F/5/S    TRAPPIST-1e  20.0  False
5        0027_01      Earth     False     F/7/P    TRAPPIST-1e  31.0  False
6        0029_01     Europa      True     B/2/P    55 Cancri e  21.0  False
7        0032_01     Europa      True     D/0/S    TRAPPIST-1e  20.0  False
8        0032_02     Europa      True     D/0/S    55 Cancri e  23.0  False
9        0033_01      Earth     False     F/7/S    55 Cancri e  24.0  False
10       0037_01      Earth     False     F/9/S    TRAPPIST-1e  19.0  False
11       0040_01     Europa     False     D/2/P    TRAPPIST-1e  45.0  False
12       0040_02     Europa     False     D/2/P    TRAPPIST-1e  44.0  False
13       0042_01       Mars      True     E/0/P    TRAPPIST-1e  46.0  False
14       0046_01      Earth     False     G/4/P    TRAPPIST-1e  21.0  False
15       0046_02      Earth     False    F/11/P    TRAPPIST-1e  27.0  False
16       0046_03      Earth     False    F/11/P    TRAPPIST-1e  20.0  False
17       0047_01     Europa      True     B/0/S    TRAPPIST-1e  44.0  False
18       0047_02     Europa     False       NaN    TRAPPIST-1e  29.0  False
19       0047_03     Europa     False     B/0/S    TRAPPIST-1e  40.0  False
20       0048_01      Earth     False     G/5/S    TRAPPIST-1e  30.0  False
21       0049_01      Earth     False     E/1/P    TRAPPIST-1e  14.0  False
22       0054_01     Europa      True     B/4/P    55 Cancri e  31.0  False
23       0054_02     Europa     False     B/4/P    55 Cancri e  27.0  False
24       0054_03     Europa     False     B/4/P    55 Cancri e  66.0  False
25       0055_01      Earth     False     G/5/P    TRAPPIST-1e  24.0  False
26       0057_01     Europa     False     C/1/P    55 Cancri e  19.0  False
27       0059_01      Earth      True     E/2/P    TRAPPIST-1e  36.0  False
28       0060_01      Earth     False    F/12/P    TRAPPIST-1e  21.0  False
29       0063_01      Earth      True     G/8/S    55 Cancri e  18.0  False
...          ...        ...       ...       ...            ...   ...    ...
4247     9216_01      Earth     False  F/1885/P    TRAPPIST-1e  22.0  False
4248     9223_01       Mars      True       NaN    TRAPPIST-1e  24.0  False
4249     9223_02       Mars      True       NaN    TRAPPIST-1e  17.0  False
4250     9228_01      Earth     False  F/1887/P    TRAPPIST-1e  21.0    NaN
4251     9229_01       Mars     False   E/605/S    TRAPPIST-1e  24.0  False
4252     9232_01      Earth     False  G/1499/P    TRAPPIST-1e  41.0  False
4253     9236_01      Earth     False  F/1790/S    TRAPPIST-1e  13.0  False
4254     9238_01      Earth     False  G/1501/P    TRAPPIST-1e  10.0  False
4255     9238_02      Earth      True  G/1501/P    55 Cancri e   3.0  False
4256     9238_03      Earth      True  G/1501/P    TRAPPIST-1e  16.0  False
4257     9238_04      Earth     False  G/1501/P    TRAPPIST-1e  26.0  False
4258     9238_05      Earth      True       NaN    TRAPPIST-1e  14.0  False
4259     9238_06      Earth     False  G/1501/P    55 Cancri e   0.0  False
4260     9238_07      Earth     False  F/1890/P    TRAPPIST-1e  32.0  False
4261     9240_01      Earth     False   E/594/P    TRAPPIST-1e  15.0  False
4262     9243_01     Europa     False   E/596/P    TRAPPIST-1e  35.0  False
4263     9245_01      Earth     False  F/1791/S    TRAPPIST-1e  20.0  False
4264     9249_01      Earth     False  G/1492/S    TRAPPIST-1e  21.0  False
4265     9255_01       Mars     False  F/1794/S    TRAPPIST-1e  32.0  False
4266     9258_01     Europa      True   E/598/P    TRAPPIST-1e  29.0  False
4267     9260_01      Earth      True  G/1503/P    55 Cancri e   3.0    NaN
4268     9262_01      Earth     False  F/1795/S    55 Cancri e  20.0  False
4269     9263_01      Earth      True  G/1495/S    TRAPPIST-1e  43.0  False
4270     9265_01       Mars     False   D/278/S    TRAPPIST-1e  43.0  False
4271     9266_01      Earth     False  F/1796/S    TRAPPIST-1e  40.0  False
4272     9266_02      Earth      True  G/1496/S    TRAPPIST-1e  34.0  False
4273     9269_01      Earth     False       NaN    TRAPPIST-1e  42.0  False
4274     9271_01       Mars      True   D/296/P    55 Cancri e   NaN  False
4275     9273_01     Europa     False   D/297/P            NaN   NaN  False
4276     9277_01      Earth      True  G/1498/S  PSO J318.5-22  43.0  False

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck                Name
0             0.0        0.0           0.0     0.0     0.0     Nelly Carsoning
1             0.0        9.0           0.0  2823.0     0.0      Lerome Peckers
2             0.0        0.0           0.0     0.0     0.0     Sabih Unhearfus
3             0.0     6652.0           0.0   181.0   585.0    Meratz Caltilter
4            10.0        0.0         635.0     0.0     0.0     Brence Harperez
5             0.0     1615.0         263.0   113.0    60.0        Karlen Ricks
6             0.0        NaN           0.0     0.0     0.0     Aldah Ainserfle
7             0.0        0.0           0.0     0.0     0.0      Acrabi Pringry
8             0.0        0.0           0.0     0.0     0.0       Dhena Pringry
9             0.0      639.0           0.0     0.0     0.0   Eliana Delazarson
10          339.0        3.0         136.0   237.0     0.0       Vivia Rickson
11          932.0       74.0           NaN     7.0  1010.0    Antino Pinoffent
12            0.0     1561.0           0.0    14.0   224.0     Jihda Pinoffent
13            0.0        0.0           0.0     0.0     0.0         Hamus Frit√©
14            0.0        0.0           0.0  1687.0    92.0       Neilda Powery
15            0.0        0.0           0.0   903.0     NaN        Glene Powery
16            2.0       12.0         253.0   457.0   690.0       Joanny Powery
17            0.0        0.0           0.0     0.0     0.0    Winonon Prucerod
18            0.0     7708.0         243.0   569.0   343.0      Muons Prucerod
19           26.0     1925.0           8.0  3144.0    63.0                 NaN
20            0.0      878.0          26.0     3.0     0.0       Tyle Deckerry
21            NaN        0.0           0.0  1609.0     0.0       Doria Flynney
22            0.0        0.0           0.0     0.0     0.0    Algedia Viouster
23            0.0     6977.0           0.0     4.0  1235.0    Alteron Viouster
24           39.0     6452.0           0.0  1409.0   155.0      Winon Viouster
25         1784.0        8.0          18.0    18.0     0.0     Brence Frederry
26          293.0     3495.0        5273.0   118.0   422.0      Gatrin Windend
27            0.0        0.0           0.0     0.0     0.0        Janne Carvis
28            0.0      619.0          12.0     3.0     0.0      Fanna Ashipeck
29            0.0        0.0           0.0     0.0     0.0    Elene Daughessey
...           ...        ...           ...     ...     ...                 ...
4247          0.0      147.0           3.0     0.0   494.0        Luise Barrez
4248          0.0        0.0           NaN     0.0     0.0          Weessh Sun
4249          0.0        0.0           0.0     0.0     0.0           Perit Sun
4250        640.0        0.0          21.0     0.0    76.0   Davis Bulliamoses
4251          NaN       32.0         282.0     1.0     0.0         Colal Brity
4252        652.0        0.0         112.0    10.0     0.0         Berly Roses
4253          0.0      873.0           0.0     1.0     0.0      Arllia Ramoran
4254          0.0        0.0           0.0     0.0     0.0     Joana Garnettiz
4255          NaN        0.0           0.0     0.0     0.0        Ricke Emenez
4256          0.0        0.0           0.0     0.0     0.0       Herina Emenez
4257        882.0        2.0           0.0     0.0     0.0       Marlie Emenez
4258          0.0        0.0           0.0     0.0     0.0       Caseye Emenez
4259          0.0        0.0           0.0     0.0     0.0    Blance Garnettiz
4260        115.0        0.0        2156.0   486.0     0.0        Camie Emenez
4261          0.0        0.0           4.0     0.0   618.0       Glendy Reenon
4262          0.0     4813.0           0.0   142.0   523.0   Sollum Pumpeshaft
4263       1272.0        3.0         543.0     0.0     0.0   Eriana Jenkinnedy
4264        147.0      603.0          20.0     0.0     0.0       Hilip Lambles
4265         46.0        3.0        1258.0     0.0     0.0          Skies Bota
4266          0.0        0.0           0.0     0.0     0.0    Beidus Siveduced
4267          0.0        0.0           0.0     0.0     0.0   Luisy Portananney
4268          0.0      601.0         103.0    35.0     0.0  Sonald Hurchrisong
4269          0.0        0.0           0.0     0.0     0.0        Loisey Heney
4270         47.0        0.0        3851.0     0.0     0.0          Toate Cure
4271          0.0      865.0           0.0     3.0     0.0         Danna Peter
4272          0.0        0.0           0.0     0.0     0.0         Jeron Peter
4273          0.0      847.0          17.0    10.0   144.0       Matty Scheron
4274          0.0        0.0           0.0     0.0     0.0         Jayrin Pore
4275          0.0     2680.0           0.0     0.0   523.0      Kitakan Conale
4276          0.0        0.0           0.0     0.0     0.0    Lilace Leonzaley

[4277 rows x 13 columns]

In [74]:
a.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez

In [75]:
a.shape

(4277, 13)

In [76]:
type(a)

pandas.core.frame.DataFrame

In [77]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 13 columns):
PassengerId     4277 non-null object
HomePlanet      4190 non-null object
CryoSleep       4184 non-null object
Cabin           4177 non-null object
Destination     4185 non-null object
Age             4186 non-null float64
VIP             4184 non-null object
RoomService     4195 non-null float64
FoodCourt       4171 non-null float64
ShoppingMall    4179 non-null float64
Spa             4176 non-null float64
VRDeck          4197 non-null float64
Name            4183 non-null object
dtypes: float64(6), object(7)
memory usage: 434.5+ KB

In [78]:
a.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name'],
      dtype='object')

In [79]:
a.isnull()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,True,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,True,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,True,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,True,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,True
20,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,True,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4247,False,False,False,False,False,False,False,False,False,False,False,False,False
4248,False,False,False,True,False,False,False,False,False,True,False,False,False
4249,False,False,False,True,False,False,False,False,False,False,False,False,False
4250,False,False,False,False,False,False,True,False,False,False,False,False,False
4251,False,False,False,False,False,False,False,True,False,False,False,False,False
4252,False,False,False,False,False,False,False,False,False,False,False,False,False
4253,False,False,False,False,False,False,False,False,False,False,False,False,False
4254,False,False,False,False,False,False,False,False,False,False,False,False,False
4255,False,False,False,False,False,False,False,True,False,False,False,False,False
4256,False,False,False,False,False,False,False,False,False,False,False,False,False
4257,False,False,False,False,False,False,False,False,False,False,False,False,False
4258,False,False,False,True,False,False,False,False,False,False,False,False,False
4259,False,False,False,False,False,False,False,False,False,False,False,False,False
4260,False,False,False,False,False,False,False,False,False,False,False,False,False
4261,False,False,False,False,False,False,False,False,False,False,False,False,False
4262,False,False,False,False,False,False,False,False,False,False,False,False,False
4263,False,False,False,False,False,False,False,False,False,False,False,False,False
4264,False,False,False,False,False,False,False,False,False,False,False,False,False
4265,False,False,False,False,False,False,False,False,False,False,False,False,False
4266,False,False,False,False,False,False,False,False,False,False,False,False,False
4267,False,False,False,False,False,False,True,False,False,False,False,False,False
4268,False,False,False,False,False,False,False,False,False,False,False,False,False
4269,False,False,False,False,False,False,False,False,False,False,False,False,False
4270,False,False,False,False,False,False,False,False,False,False,False,False,False
4271,False,False,False,False,False,False,False,False,False,False,False,False,False
4272,False,False,False,False,False,False,False,False,False,False,False,False,False
4273,False,False,False,True,False,False,False,False,False,False,False,False,False
4274,False,False,False,False,False,True,False,False,False,False,False,False,False
4275,False,False,False,False,True,True,False,False,False,False,False,False,False
4276,False,False,False,False,False,False,False,False,False,False,False,False,False

In [80]:
a.isnull

<bound method DataFrame.isnull of      PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0013_01      Earth      True     G/3/S    TRAPPIST-1e  27.0  False
1        0018_01      Earth     False     F/4/S    TRAPPIST-1e  19.0  False
2        0019_01     Europa      True     C/0/S    55 Cancri e  31.0  False
3        0021_01     Europa     False     C/1/S    TRAPPIST-1e  38.0  False
4        0023_01      Earth     False     F/5/S    TRAPPIST-1e  20.0  False
5        0027_01      Earth     False     F/7/P    TRAPPIST-1e  31.0  False
6        0029_01     Europa      True     B/2/P    55 Cancri e  21.0  False
7        0032_01     Europa      True     D/0/S    TRAPPIST-1e  20.0  False
8        0032_02     Europa      True     D/0/S    55 Cancri e  23.0  False
9        0033_01      Earth     False     F/7/S    55 Cancri e  24.0  False
10       0037_01      Earth     False     F/9/S    TRAPPIST-1e  19.0  False
11       0040_01     Europa     False     D/2/P    TRAPPIST-1e  45.0  False
12       0040_02     Europa     False     D/2/P    TRAPPIST-1e  44.0  False
13       0042_01       Mars      True     E/0/P    TRAPPIST-1e  46.0  False
14       0046_01      Earth     False     G/4/P    TRAPPIST-1e  21.0  False
15       0046_02      Earth     False    F/11/P    TRAPPIST-1e  27.0  False
16       0046_03      Earth     False    F/11/P    TRAPPIST-1e  20.0  False
17       0047_01     Europa      True     B/0/S    TRAPPIST-1e  44.0  False
18       0047_02     Europa     False       NaN    TRAPPIST-1e  29.0  False
19       0047_03     Europa     False     B/0/S    TRAPPIST-1e  40.0  False
20       0048_01      Earth     False     G/5/S    TRAPPIST-1e  30.0  False
21       0049_01      Earth     False     E/1/P    TRAPPIST-1e  14.0  False
22       0054_01     Europa      True     B/4/P    55 Cancri e  31.0  False
23       0054_02     Europa     False     B/4/P    55 Cancri e  27.0  False
24       0054_03     Europa     False     B/4/P    55 Cancri e  66.0  False
25       0055_01      Earth     False     G/5/P    TRAPPIST-1e  24.0  False
26       0057_01     Europa     False     C/1/P    55 Cancri e  19.0  False
27       0059_01      Earth      True     E/2/P    TRAPPIST-1e  36.0  False
28       0060_01      Earth     False    F/12/P    TRAPPIST-1e  21.0  False
29       0063_01      Earth      True     G/8/S    55 Cancri e  18.0  False
...          ...        ...       ...       ...            ...   ...    ...
4247     9216_01      Earth     False  F/1885/P    TRAPPIST-1e  22.0  False
4248     9223_01       Mars      True       NaN    TRAPPIST-1e  24.0  False
4249     9223_02       Mars      True       NaN    TRAPPIST-1e  17.0  False
4250     9228_01      Earth     False  F/1887/P    TRAPPIST-1e  21.0    NaN
4251     9229_01       Mars     False   E/605/S    TRAPPIST-1e  24.0  False
4252     9232_01      Earth     False  G/1499/P    TRAPPIST-1e  41.0  False
4253     9236_01      Earth     False  F/1790/S    TRAPPIST-1e  13.0  False
4254     9238_01      Earth     False  G/1501/P    TRAPPIST-1e  10.0  False
4255     9238_02      Earth      True  G/1501/P    55 Cancri e   3.0  False
4256     9238_03      Earth      True  G/1501/P    TRAPPIST-1e  16.0  False
4257     9238_04      Earth     False  G/1501/P    TRAPPIST-1e  26.0  False
4258     9238_05      Earth      True       NaN    TRAPPIST-1e  14.0  False
4259     9238_06      Earth     False  G/1501/P    55 Cancri e   0.0  False
4260     9238_07      Earth     False  F/1890/P    TRAPPIST-1e  32.0  False
4261     9240_01      Earth     False   E/594/P    TRAPPIST-1e  15.0  False
4262     9243_01     Europa     False   E/596/P    TRAPPIST-1e  35.0  False
4263     9245_01      Earth     False  F/1791/S    TRAPPIST-1e  20.0  False
4264     9249_01      Earth     False  G/1492/S    TRAPPIST-1e  21.0  False
4265     9255_01       Mars     False  F/1794/S    TRAPPIST-1e  32.0  False
4266     9258_01     Europa      True   E/598/P    TRAPPIST-1e  29.0  False
4267     9260_01      Earth      True  G/1503/P    55 Cancri e   3.0    NaN
4268     9262_01      Earth     False  F/1795/S    55 Cancri e  20.0  False
4269     9263_01      Earth      True  G/1495/S    TRAPPIST-1e  43.0  False
4270     9265_01       Mars     False   D/278/S    TRAPPIST-1e  43.0  False
4271     9266_01      Earth     False  F/1796/S    TRAPPIST-1e  40.0  False
4272     9266_02      Earth      True  G/1496/S    TRAPPIST-1e  34.0  False
4273     9269_01      Earth     False       NaN    TRAPPIST-1e  42.0  False
4274     9271_01       Mars      True   D/296/P    55 Cancri e   NaN  False
4275     9273_01     Europa     False   D/297/P            NaN   NaN  False
4276     9277_01      Earth      True  G/1498/S  PSO J318.5-22  43.0  False

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck                Name
0             0.0        0.0           0.0     0.0     0.0     Nelly Carsoning
1             0.0        9.0           0.0  2823.0     0.0      Lerome Peckers
2             0.0        0.0           0.0     0.0     0.0     Sabih Unhearfus
3             0.0     6652.0           0.0   181.0   585.0    Meratz Caltilter
4            10.0        0.0         635.0     0.0     0.0     Brence Harperez
5             0.0     1615.0         263.0   113.0    60.0        Karlen Ricks
6             0.0        NaN           0.0     0.0     0.0     Aldah Ainserfle
7             0.0        0.0           0.0     0.0     0.0      Acrabi Pringry
8             0.0        0.0           0.0     0.0     0.0       Dhena Pringry
9             0.0      639.0           0.0     0.0     0.0   Eliana Delazarson
10          339.0        3.0         136.0   237.0     0.0       Vivia Rickson
11          932.0       74.0           NaN     7.0  1010.0    Antino Pinoffent
12            0.0     1561.0           0.0    14.0   224.0     Jihda Pinoffent
13            0.0        0.0           0.0     0.0     0.0         Hamus Frit√©
14            0.0        0.0           0.0  1687.0    92.0       Neilda Powery
15            0.0        0.0           0.0   903.0     NaN        Glene Powery
16            2.0       12.0         253.0   457.0   690.0       Joanny Powery
17            0.0        0.0           0.0     0.0     0.0    Winonon Prucerod
18            0.0     7708.0         243.0   569.0   343.0      Muons Prucerod
19           26.0     1925.0           8.0  3144.0    63.0                 NaN
20            0.0      878.0          26.0     3.0     0.0       Tyle Deckerry
21            NaN        0.0           0.0  1609.0     0.0       Doria Flynney
22            0.0        0.0           0.0     0.0     0.0    Algedia Viouster
23            0.0     6977.0           0.0     4.0  1235.0    Alteron Viouster
24           39.0     6452.0           0.0  1409.0   155.0      Winon Viouster
25         1784.0        8.0          18.0    18.0     0.0     Brence Frederry
26          293.0     3495.0        5273.0   118.0   422.0      Gatrin Windend
27            0.0        0.0           0.0     0.0     0.0        Janne Carvis
28            0.0      619.0          12.0     3.0     0.0      Fanna Ashipeck
29            0.0        0.0           0.0     0.0     0.0    Elene Daughessey
...           ...        ...           ...     ...     ...                 ...
4247          0.0      147.0           3.0     0.0   494.0        Luise Barrez
4248          0.0        0.0           NaN     0.0     0.0          Weessh Sun
4249          0.0        0.0           0.0     0.0     0.0           Perit Sun
4250        640.0        0.0          21.0     0.0    76.0   Davis Bulliamoses
4251          NaN       32.0         282.0     1.0     0.0         Colal Brity
4252        652.0        0.0         112.0    10.0     0.0         Berly Roses
4253          0.0      873.0           0.0     1.0     0.0      Arllia Ramoran
4254          0.0        0.0           0.0     0.0     0.0     Joana Garnettiz
4255          NaN        0.0           0.0     0.0     0.0        Ricke Emenez
4256          0.0        0.0           0.0     0.0     0.0       Herina Emenez
4257        882.0        2.0           0.0     0.0     0.0       Marlie Emenez
4258          0.0        0.0           0.0     0.0     0.0       Caseye Emenez
4259          0.0        0.0           0.0     0.0     0.0    Blance Garnettiz
4260        115.0        0.0        2156.0   486.0     0.0        Camie Emenez
4261          0.0        0.0           4.0     0.0   618.0       Glendy Reenon
4262          0.0     4813.0           0.0   142.0   523.0   Sollum Pumpeshaft
4263       1272.0        3.0         543.0     0.0     0.0   Eriana Jenkinnedy
4264        147.0      603.0          20.0     0.0     0.0       Hilip Lambles
4265         46.0        3.0        1258.0     0.0     0.0          Skies Bota
4266          0.0        0.0           0.0     0.0     0.0    Beidus Siveduced
4267          0.0        0.0           0.0     0.0     0.0   Luisy Portananney
4268          0.0      601.0         103.0    35.0     0.0  Sonald Hurchrisong
4269          0.0        0.0           0.0     0.0     0.0        Loisey Heney
4270         47.0        0.0        3851.0     0.0     0.0          Toate Cure
4271          0.0      865.0           0.0     3.0     0.0         Danna Peter
4272          0.0        0.0           0.0     0.0     0.0         Jeron Peter
4273          0.0      847.0          17.0    10.0   144.0       Matty Scheron
4274          0.0        0.0           0.0     0.0     0.0         Jayrin Pore
4275          0.0     2680.0           0.0     0.0   523.0      Kitakan Conale
4276          0.0        0.0           0.0     0.0     0.0    Lilace Leonzaley

[4277 rows x 13 columns]>

In [81]:
a.shape[1]

13

In [82]:
a['PassengerId'].value_counts
print(a)

     PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0013_01      Earth      True     G/3/S    TRAPPIST-1e  27.0  False
1        0018_01      Earth     False     F/4/S    TRAPPIST-1e  19.0  False
2        0019_01     Europa      True     C/0/S    55 Cancri e  31.0  False
3        0021_01     Europa     False     C/1/S    TRAPPIST-1e  38.0  False
4        0023_01      Earth     False     F/5/S    TRAPPIST-1e  20.0  False
5        0027_01      Earth     False     F/7/P    TRAPPIST-1e  31.0  False
6        0029_01     Europa      True     B/2/P    55 Cancri e  21.0  False
7        0032_01     Europa      True     D/0/S    TRAPPIST-1e  20.0  False
8        0032_02     Europa      True     D/0/S    55 Cancri e  23.0  False
9        0033_01      Earth     False     F/7/S    55 Cancri e  24.0  False
10       0037_01      Earth     False     F/9/S    TRAPPIST-1e  19.0  False
11       0040_01     Europa     False     D/2/P    TRAPPIST-1e  45.0  False
12       0040_02     Europa     False     D/2/P    TRAPPIST-1e  44.0  False
13       0042_01       Mars      True     E/0/P    TRAPPIST-1e  46.0  False
14       0046_01      Earth     False     G/4/P    TRAPPIST-1e  21.0  False
15       0046_02      Earth     False    F/11/P    TRAPPIST-1e  27.0  False
16       0046_03      Earth     False    F/11/P    TRAPPIST-1e  20.0  False
17       0047_01     Europa      True     B/0/S    TRAPPIST-1e  44.0  False
18       0047_02     Europa     False       NaN    TRAPPIST-1e  29.0  False
19       0047_03     Europa     False     B/0/S    TRAPPIST-1e  40.0  False
20       0048_01      Earth     False     G/5/S    TRAPPIST-1e  30.0  False
21       0049_01      Earth     False     E/1/P    TRAPPIST-1e  14.0  False
22       0054_01     Europa      True     B/4/P    55 Cancri e  31.0  False
23       0054_02     Europa     False     B/4/P    55 Cancri e  27.0  False
24       0054_03     Europa     False     B/4/P    55 Cancri e  66.0  False
25       0055_01      Earth     False     G/5/P    TRAPPIST-1e  24.0  False
26       0057_01     Europa     False     C/1/P    55 Cancri e  19.0  False
27       0059_01      Earth      True     E/2/P    TRAPPIST-1e  36.0  False
28       0060_01      Earth     False    F/12/P    TRAPPIST-1e  21.0  False
29       0063_01      Earth      True     G/8/S    55 Cancri e  18.0  False
...          ...        ...       ...       ...            ...   ...    ...
4247     9216_01      Earth     False  F/1885/P    TRAPPIST-1e  22.0  False
4248     9223_01       Mars      True       NaN    TRAPPIST-1e  24.0  False
4249     9223_02       Mars      True       NaN    TRAPPIST-1e  17.0  False
4250     9228_01      Earth     False  F/1887/P    TRAPPIST-1e  21.0    NaN
4251     9229_01       Mars     False   E/605/S    TRAPPIST-1e  24.0  False
4252     9232_01      Earth     False  G/1499/P    TRAPPIST-1e  41.0  False
4253     9236_01      Earth     False  F/1790/S    TRAPPIST-1e  13.0  False
4254     9238_01      Earth     False  G/1501/P    TRAPPIST-1e  10.0  False
4255     9238_02      Earth      True  G/1501/P    55 Cancri e   3.0  False
4256     9238_03      Earth      True  G/1501/P    TRAPPIST-1e  16.0  False
4257     9238_04      Earth     False  G/1501/P    TRAPPIST-1e  26.0  False
4258     9238_05      Earth      True       NaN    TRAPPIST-1e  14.0  False
4259     9238_06      Earth     False  G/1501/P    55 Cancri e   0.0  False
4260     9238_07      Earth     False  F/1890/P    TRAPPIST-1e  32.0  False
4261     9240_01      Earth     False   E/594/P    TRAPPIST-1e  15.0  False
4262     9243_01     Europa     False   E/596/P    TRAPPIST-1e  35.0  False
4263     9245_01      Earth     False  F/1791/S    TRAPPIST-1e  20.0  False
4264     9249_01      Earth     False  G/1492/S    TRAPPIST-1e  21.0  False
4265     9255_01       Mars     False  F/1794/S    TRAPPIST-1e  32.0  False
4266     9258_01     Europa      True   E/598/P    TRAPPIST-1e  29.0  False
4267     9260_01      Earth      True  G/1503/P    55 Cancri e   3.0    NaN
4268     9262_01      Earth     False  F/1795/S    55 Cancri e  20.0  False
4269     9263_01      Earth      True  G/1495/S    TRAPPIST-1e  43.0  False
4270     9265_01       Mars     False   D/278/S    TRAPPIST-1e  43.0  False
4271     9266_01      Earth     False  F/1796/S    TRAPPIST-1e  40.0  False
4272     9266_02      Earth      True  G/1496/S    TRAPPIST-1e  34.0  False
4273     9269_01      Earth     False       NaN    TRAPPIST-1e  42.0  False
4274     9271_01       Mars      True   D/296/P    55 Cancri e   NaN  False
4275     9273_01     Europa     False   D/297/P            NaN   NaN  False
4276     9277_01      Earth      True  G/1498/S  PSO J318.5-22  43.0  False

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck                Name
0             0.0        0.0           0.0     0.0     0.0     Nelly Carsoning
1             0.0        9.0           0.0  2823.0     0.0      Lerome Peckers
2             0.0        0.0           0.0     0.0     0.0     Sabih Unhearfus
3             0.0     6652.0           0.0   181.0   585.0    Meratz Caltilter
4            10.0        0.0         635.0     0.0     0.0     Brence Harperez
5             0.0     1615.0         263.0   113.0    60.0        Karlen Ricks
6             0.0        NaN           0.0     0.0     0.0     Aldah Ainserfle
7             0.0        0.0           0.0     0.0     0.0      Acrabi Pringry
8             0.0        0.0           0.0     0.0     0.0       Dhena Pringry
9             0.0      639.0           0.0     0.0     0.0   Eliana Delazarson
10          339.0        3.0         136.0   237.0     0.0       Vivia Rickson
11          932.0       74.0           NaN     7.0  1010.0    Antino Pinoffent
12            0.0     1561.0           0.0    14.0   224.0     Jihda Pinoffent
13            0.0        0.0           0.0     0.0     0.0         Hamus Frit√©
14            0.0        0.0           0.0  1687.0    92.0       Neilda Powery
15            0.0        0.0           0.0   903.0     NaN        Glene Powery
16            2.0       12.0         253.0   457.0   690.0       Joanny Powery
17            0.0        0.0           0.0     0.0     0.0    Winonon Prucerod
18            0.0     7708.0         243.0   569.0   343.0      Muons Prucerod
19           26.0     1925.0           8.0  3144.0    63.0                 NaN
20            0.0      878.0          26.0     3.0     0.0       Tyle Deckerry
21            NaN        0.0           0.0  1609.0     0.0       Doria Flynney
22            0.0        0.0           0.0     0.0     0.0    Algedia Viouster
23            0.0     6977.0           0.0     4.0  1235.0    Alteron Viouster
24           39.0     6452.0           0.0  1409.0   155.0      Winon Viouster
25         1784.0        8.0          18.0    18.0     0.0     Brence Frederry
26          293.0     3495.0        5273.0   118.0   422.0      Gatrin Windend
27            0.0        0.0           0.0     0.0     0.0        Janne Carvis
28            0.0      619.0          12.0     3.0     0.0      Fanna Ashipeck
29            0.0        0.0           0.0     0.0     0.0    Elene Daughessey
...           ...        ...           ...     ...     ...                 ...
4247          0.0      147.0           3.0     0.0   494.0        Luise Barrez
4248          0.0        0.0           NaN     0.0     0.0          Weessh Sun
4249          0.0        0.0           0.0     0.0     0.0           Perit Sun
4250        640.0        0.0          21.0     0.0    76.0   Davis Bulliamoses
4251          NaN       32.0         282.0     1.0     0.0         Colal Brity
4252        652.0        0.0         112.0    10.0     0.0         Berly Roses
4253          0.0      873.0           0.0     1.0     0.0      Arllia Ramoran
4254          0.0        0.0           0.0     0.0     0.0     Joana Garnettiz
4255          NaN        0.0           0.0     0.0     0.0        Ricke Emenez
4256          0.0        0.0           0.0     0.0     0.0       Herina Emenez
4257        882.0        2.0           0.0     0.0     0.0       Marlie Emenez
4258          0.0        0.0           0.0     0.0     0.0       Caseye Emenez
4259          0.0        0.0           0.0     0.0     0.0    Blance Garnettiz
4260        115.0        0.0        2156.0   486.0     0.0        Camie Emenez
4261          0.0        0.0           4.0     0.0   618.0       Glendy Reenon
4262          0.0     4813.0           0.0   142.0   523.0   Sollum Pumpeshaft
4263       1272.0        3.0         543.0     0.0     0.0   Eriana Jenkinnedy
4264        147.0      603.0          20.0     0.0     0.0       Hilip Lambles
4265         46.0        3.0        1258.0     0.0     0.0          Skies Bota
4266          0.0        0.0           0.0     0.0     0.0    Beidus Siveduced
4267          0.0        0.0           0.0     0.0     0.0   Luisy Portananney
4268          0.0      601.0         103.0    35.0     0.0  Sonald Hurchrisong
4269          0.0        0.0           0.0     0.0     0.0        Loisey Heney
4270         47.0        0.0        3851.0     0.0     0.0          Toate Cure
4271          0.0      865.0           0.0     3.0     0.0         Danna Peter
4272          0.0        0.0           0.0     0.0     0.0         Jeron Peter
4273          0.0      847.0          17.0    10.0   144.0       Matty Scheron
4274          0.0        0.0           0.0     0.0     0.0         Jayrin Pore
4275          0.0     2680.0           0.0     0.0   523.0      Kitakan Conale
4276          0.0        0.0           0.0     0.0     0.0    Lilace Leonzaley

[4277 rows x 13 columns]

In [83]:
df2=a.drop(['FoodCourt'],axis=1)
print(df2)

     PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0013_01      Earth      True     G/3/S    TRAPPIST-1e  27.0  False
1        0018_01      Earth     False     F/4/S    TRAPPIST-1e  19.0  False
2        0019_01     Europa      True     C/0/S    55 Cancri e  31.0  False
3        0021_01     Europa     False     C/1/S    TRAPPIST-1e  38.0  False
4        0023_01      Earth     False     F/5/S    TRAPPIST-1e  20.0  False
5        0027_01      Earth     False     F/7/P    TRAPPIST-1e  31.0  False
6        0029_01     Europa      True     B/2/P    55 Cancri e  21.0  False
7        0032_01     Europa      True     D/0/S    TRAPPIST-1e  20.0  False
8        0032_02     Europa      True     D/0/S    55 Cancri e  23.0  False
9        0033_01      Earth     False     F/7/S    55 Cancri e  24.0  False
10       0037_01      Earth     False     F/9/S    TRAPPIST-1e  19.0  False
11       0040_01     Europa     False     D/2/P    TRAPPIST-1e  45.0  False
12       0040_02     Europa     False     D/2/P    TRAPPIST-1e  44.0  False
13       0042_01       Mars      True     E/0/P    TRAPPIST-1e  46.0  False
14       0046_01      Earth     False     G/4/P    TRAPPIST-1e  21.0  False
15       0046_02      Earth     False    F/11/P    TRAPPIST-1e  27.0  False
16       0046_03      Earth     False    F/11/P    TRAPPIST-1e  20.0  False
17       0047_01     Europa      True     B/0/S    TRAPPIST-1e  44.0  False
18       0047_02     Europa     False       NaN    TRAPPIST-1e  29.0  False
19       0047_03     Europa     False     B/0/S    TRAPPIST-1e  40.0  False
20       0048_01      Earth     False     G/5/S    TRAPPIST-1e  30.0  False
21       0049_01      Earth     False     E/1/P    TRAPPIST-1e  14.0  False
22       0054_01     Europa      True     B/4/P    55 Cancri e  31.0  False
23       0054_02     Europa     False     B/4/P    55 Cancri e  27.0  False
24       0054_03     Europa     False     B/4/P    55 Cancri e  66.0  False
25       0055_01      Earth     False     G/5/P    TRAPPIST-1e  24.0  False
26       0057_01     Europa     False     C/1/P    55 Cancri e  19.0  False
27       0059_01      Earth      True     E/2/P    TRAPPIST-1e  36.0  False
28       0060_01      Earth     False    F/12/P    TRAPPIST-1e  21.0  False
29       0063_01      Earth      True     G/8/S    55 Cancri e  18.0  False
...          ...        ...       ...       ...            ...   ...    ...
4247     9216_01      Earth     False  F/1885/P    TRAPPIST-1e  22.0  False
4248     9223_01       Mars      True       NaN    TRAPPIST-1e  24.0  False
4249     9223_02       Mars      True       NaN    TRAPPIST-1e  17.0  False
4250     9228_01      Earth     False  F/1887/P    TRAPPIST-1e  21.0    NaN
4251     9229_01       Mars     False   E/605/S    TRAPPIST-1e  24.0  False
4252     9232_01      Earth     False  G/1499/P    TRAPPIST-1e  41.0  False
4253     9236_01      Earth     False  F/1790/S    TRAPPIST-1e  13.0  False
4254     9238_01      Earth     False  G/1501/P    TRAPPIST-1e  10.0  False
4255     9238_02      Earth      True  G/1501/P    55 Cancri e   3.0  False
4256     9238_03      Earth      True  G/1501/P    TRAPPIST-1e  16.0  False
4257     9238_04      Earth     False  G/1501/P    TRAPPIST-1e  26.0  False
4258     9238_05      Earth      True       NaN    TRAPPIST-1e  14.0  False
4259     9238_06      Earth     False  G/1501/P    55 Cancri e   0.0  False
4260     9238_07      Earth     False  F/1890/P    TRAPPIST-1e  32.0  False
4261     9240_01      Earth     False   E/594/P    TRAPPIST-1e  15.0  False
4262     9243_01     Europa     False   E/596/P    TRAPPIST-1e  35.0  False
4263     9245_01      Earth     False  F/1791/S    TRAPPIST-1e  20.0  False
4264     9249_01      Earth     False  G/1492/S    TRAPPIST-1e  21.0  False
4265     9255_01       Mars     False  F/1794/S    TRAPPIST-1e  32.0  False
4266     9258_01     Europa      True   E/598/P    TRAPPIST-1e  29.0  False
4267     9260_01      Earth      True  G/1503/P    55 Cancri e   3.0    NaN
4268     9262_01      Earth     False  F/1795/S    55 Cancri e  20.0  False
4269     9263_01      Earth      True  G/1495/S    TRAPPIST-1e  43.0  False
4270     9265_01       Mars     False   D/278/S    TRAPPIST-1e  43.0  False
4271     9266_01      Earth     False  F/1796/S    TRAPPIST-1e  40.0  False
4272     9266_02      Earth      True  G/1496/S    TRAPPIST-1e  34.0  False
4273     9269_01      Earth     False       NaN    TRAPPIST-1e  42.0  False
4274     9271_01       Mars      True   D/296/P    55 Cancri e   NaN  False
4275     9273_01     Europa     False   D/297/P            NaN   NaN  False
4276     9277_01      Earth      True  G/1498/S  PSO J318.5-22  43.0  False

      RoomService  ShoppingMall     Spa  VRDeck                Name
0             0.0           0.0     0.0     0.0     Nelly Carsoning
1             0.0           0.0  2823.0     0.0      Lerome Peckers
2             0.0           0.0     0.0     0.0     Sabih Unhearfus
3             0.0           0.0   181.0   585.0    Meratz Caltilter
4            10.0         635.0     0.0     0.0     Brence Harperez
5             0.0         263.0   113.0    60.0        Karlen Ricks
6             0.0           0.0     0.0     0.0     Aldah Ainserfle
7             0.0           0.0     0.0     0.0      Acrabi Pringry
8             0.0           0.0     0.0     0.0       Dhena Pringry
9             0.0           0.0     0.0     0.0   Eliana Delazarson
10          339.0         136.0   237.0     0.0       Vivia Rickson
11          932.0           NaN     7.0  1010.0    Antino Pinoffent
12            0.0           0.0    14.0   224.0     Jihda Pinoffent
13            0.0           0.0     0.0     0.0         Hamus Frit√©
14            0.0           0.0  1687.0    92.0       Neilda Powery
15            0.0           0.0   903.0     NaN        Glene Powery
16            2.0         253.0   457.0   690.0       Joanny Powery
17            0.0           0.0     0.0     0.0    Winonon Prucerod
18            0.0         243.0   569.0   343.0      Muons Prucerod
19           26.0           8.0  3144.0    63.0                 NaN
20            0.0          26.0     3.0     0.0       Tyle Deckerry
21            NaN           0.0  1609.0     0.0       Doria Flynney
22            0.0           0.0     0.0     0.0    Algedia Viouster
23            0.0           0.0     4.0  1235.0    Alteron Viouster
24           39.0           0.0  1409.0   155.0      Winon Viouster
25         1784.0          18.0    18.0     0.0     Brence Frederry
26          293.0        5273.0   118.0   422.0      Gatrin Windend
27            0.0           0.0     0.0     0.0        Janne Carvis
28            0.0          12.0     3.0     0.0      Fanna Ashipeck
29            0.0           0.0     0.0     0.0    Elene Daughessey
...           ...           ...     ...     ...                 ...
4247          0.0           3.0     0.0   494.0        Luise Barrez
4248          0.0           NaN     0.0     0.0          Weessh Sun
4249          0.0           0.0     0.0     0.0           Perit Sun
4250        640.0          21.0     0.0    76.0   Davis Bulliamoses
4251          NaN         282.0     1.0     0.0         Colal Brity
4252        652.0         112.0    10.0     0.0         Berly Roses
4253          0.0           0.0     1.0     0.0      Arllia Ramoran
4254          0.0           0.0     0.0     0.0     Joana Garnettiz
4255          NaN           0.0     0.0     0.0        Ricke Emenez
4256          0.0           0.0     0.0     0.0       Herina Emenez
4257        882.0           0.0     0.0     0.0       Marlie Emenez
4258          0.0           0.0     0.0     0.0       Caseye Emenez
4259          0.0           0.0     0.0     0.0    Blance Garnettiz
4260        115.0        2156.0   486.0     0.0        Camie Emenez
4261          0.0           4.0     0.0   618.0       Glendy Reenon
4262          0.0           0.0   142.0   523.0   Sollum Pumpeshaft
4263       1272.0         543.0     0.0     0.0   Eriana Jenkinnedy
4264        147.0          20.0     0.0     0.0       Hilip Lambles
4265         46.0        1258.0     0.0     0.0          Skies Bota
4266          0.0           0.0     0.0     0.0    Beidus Siveduced
4267          0.0           0.0     0.0     0.0   Luisy Portananney
4268          0.0         103.0    35.0     0.0  Sonald Hurchrisong
4269          0.0           0.0     0.0     0.0        Loisey Heney
4270         47.0        3851.0     0.0     0.0          Toate Cure
4271          0.0           0.0     3.0     0.0         Danna Peter
4272          0.0           0.0     0.0     0.0         Jeron Peter
4273          0.0          17.0    10.0   144.0       Matty Scheron
4274          0.0           0.0     0.0     0.0         Jayrin Pore
4275          0.0           0.0     0.0   523.0      Kitakan Conale
4276          0.0           0.0     0.0     0.0    Lilace Leonzaley

[4277 rows x 12 columns]

In [84]:
x=pd.DataFrame(a[ 'HomePlanet'])

In [85]:
y=pd.DataFrame(a['Spa'])

In [86]:
x

     HomePlanet
0         Earth
1         Earth
2        Europa
3        Europa
4         Earth
5         Earth
6        Europa
7        Europa
8        Europa
9         Earth
10        Earth
11       Europa
12       Europa
13         Mars
14        Earth
15        Earth
16        Earth
17       Europa
18       Europa
19       Europa
20        Earth
21        Earth
22       Europa
23       Europa
24       Europa
25        Earth
26       Europa
27        Earth
28        Earth
29        Earth
...         ...
4247      Earth
4248       Mars
4249       Mars
4250      Earth
4251       Mars
4252      Earth
4253      Earth
4254      Earth
4255      Earth
4256      Earth
4257      Earth
4258      Earth
4259      Earth
4260      Earth
4261      Earth
4262     Europa
4263      Earth
4264      Earth
4265       Mars
4266     Europa
4267      Earth
4268      Earth
4269      Earth
4270       Mars
4271      Earth
4272      Earth
4273      Earth
4274       Mars
4275     Europa
4276      Earth

[4277 rows x 1 columns]

In [87]:
y

         Spa
0        0.0
1     2823.0
2        0.0
3      181.0
4        0.0
5      113.0
6        0.0
7        0.0
8        0.0
9        0.0
10     237.0
11       7.0
12      14.0
13       0.0
14    1687.0
15     903.0
16     457.0
17       0.0
18     569.0
19    3144.0
20       3.0
21    1609.0
22       0.0
23       4.0
24    1409.0
25      18.0
26     118.0
27       0.0
28       3.0
29       0.0
...      ...
4247     0.0
4248     0.0
4249     0.0
4250     0.0
4251     1.0
4252    10.0
4253     1.0
4254     0.0
4255     0.0
4256     0.0
4257     0.0
4258     0.0
4259     0.0
4260   486.0
4261     0.0
4262   142.0
4263     0.0
4264     0.0
4265     0.0
4266     0.0
4267     0.0
4268    35.0
4269     0.0
4270     0.0
4271     3.0
4272     0.0
4273    10.0
4274     0.0
4275     0.0
4276     0.0

[4277 rows x 1 columns]

In [88]:
type(x)

pandas.core.frame.DataFrame

In [89]:
type(y)

pandas.core.frame.DataFrame

In [90]:
x = a.iloc[:, :-1].values 
print(x)

[['0013_01' 'Earth' True ... 0.0 0.0 0.0]
 ['0018_01' 'Earth' False ... 0.0 2823.0 0.0]
 ['0019_01' 'Europa' True ... 0.0 0.0 0.0]
 ...
 ['9271_01' 'Mars' True ... 0.0 0.0 0.0]
 ['9273_01' 'Europa' False ... 0.0 0.0 523.0]
 ['9277_01' 'Earth' True ... 0.0 0.0 0.0]]

In [91]:
y =a.iloc[:, -1].values
print(y)

['Nelly Carsoning' 'Lerome Peckers' 'Sabih Unhearfus' ... 'Jayrin Pore'
 'Kitakan Conale' 'Lilace Leonzaley']

In [92]:
### read train file

In [93]:
d=pd.read_csv('train.csv')
print(d)

     PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False
5        0005_01      Earth     False     F/0/P  PSO J318.5-22  44.0  False
6        0006_01      Earth     False     F/2/S    TRAPPIST-1e  26.0  False
7        0006_02      Earth      True     G/0/S    TRAPPIST-1e  28.0  False
8        0007_01      Earth     False     F/3/S    TRAPPIST-1e  35.0  False
9        0008_01     Europa      True     B/1/P    55 Cancri e  14.0  False
10       0008_02     Europa      True     B/1/P    TRAPPIST-1e  34.0  False
11       0008_03     Europa     False     B/1/P    55 Cancri e  45.0  False
12       0009_01       Mars     False     F/1/P    TRAPPIST-1e  32.0  False
13       0010_01      Earth     False     G/1/S    TRAPPIST-1e  48.0  False
14       0011_01      Earth     False     F/2/P    TRAPPIST-1e  28.0  False
15       0012_01      Earth     False       NaN    TRAPPIST-1e  31.0  False
16       0014_01       Mars     False     F/3/P    55 Cancri e  27.0  False
17       0015_01      Earth     False     F/4/P    55 Cancri e  24.0  False
18       0016_01       Mars      True     F/5/P    TRAPPIST-1e  45.0  False
19       0017_01      Earth     False     G/0/P    TRAPPIST-1e   0.0  False
20       0017_02      Earth     False     F/6/P    55 Cancri e  14.0  False
21       0020_01      Earth      True     E/0/S    TRAPPIST-1e   1.0  False
22       0020_02      Earth      True     E/0/S    55 Cancri e  49.0  False
23       0020_03      Earth      True     E/0/S    55 Cancri e  29.0  False
24       0020_04      Earth     False     E/0/S    TRAPPIST-1e  10.0  False
25       0020_05      Earth      True     E/0/S  PSO J318.5-22   1.0  False
26       0020_06      Earth     False     E/0/S    TRAPPIST-1e   7.0  False
27       0022_01       Mars     False     D/0/P    TRAPPIST-1e  21.0  False
28       0024_01     Europa      True     C/2/S    TRAPPIST-1e  62.0  False
29       0025_01      Earth     False     F/6/S    TRAPPIST-1e  15.0  False
...          ...        ...       ...       ...            ...   ...    ...
8663     9244_01      Earth      True  G/1489/S  PSO J318.5-22  13.0  False
8664     9246_01      Earth       NaN  G/1490/S    TRAPPIST-1e  32.0  False
8665     9247_01      Earth      True  G/1491/S    TRAPPIST-1e  33.0  False
8666     9248_01        NaN     False  F/1792/S    55 Cancri e  38.0    NaN
8667     9250_01     Europa     False   E/597/P    TRAPPIST-1e  29.0  False
8668     9251_01       Mars      True  F/1793/S    TRAPPIST-1e  25.0  False
8669     9252_01     Europa     False   B/301/P    55 Cancri e  26.0  False
8670     9252_02     Europa      True   B/301/P    55 Cancri e  19.0  False
8671     9253_01      Earth      True  G/1493/S  PSO J318.5-22  16.0  False
8672     9254_01      Earth      True  G/1502/P  PSO J318.5-22  61.0  False
8673     9256_01      Earth      True  G/1494/S    TRAPPIST-1e  28.0  False
8674     9257_01        NaN     False  F/1892/P    TRAPPIST-1e  13.0  False
8675     9259_01      Earth       NaN  F/1893/P    TRAPPIST-1e  44.0  False
8676     9261_01      Earth      True  G/1504/P  PSO J318.5-22  22.0  False
8677     9264_01     Europa      True   E/606/S    55 Cancri e  30.0  False
8678     9267_01     Europa      True   E/607/S    TRAPPIST-1e  21.0  False
8679     9267_02     Europa      True   E/607/S    TRAPPIST-1e  20.0  False
8680     9268_01      Earth      True  G/1505/P    TRAPPIST-1e  31.0  False
8681     9270_01      Earth      True  G/1497/S    55 Cancri e  33.0  False
8682     9272_01      Earth     False  G/1507/P    TRAPPIST-1e  26.0  False
8683     9272_02      Earth     False  F/1894/P    TRAPPIST-1e  21.0  False
8684     9274_01        NaN      True  G/1508/P    TRAPPIST-1e  23.0  False
8685     9275_01     Europa     False    A/97/P    TRAPPIST-1e   0.0  False
8686     9275_02     Europa     False    A/97/P    TRAPPIST-1e  32.0  False
8687     9275_03     Europa       NaN    A/97/P    TRAPPIST-1e  30.0  False
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  \
0             0.0        0.0           0.0     0.0     0.0
1           109.0        9.0          25.0   549.0    44.0
2            43.0     3576.0           0.0  6715.0    49.0
3             0.0     1283.0         371.0  3329.0   193.0
4           303.0       70.0         151.0   565.0     2.0
5             0.0      483.0           0.0   291.0     0.0
6            42.0     1539.0           3.0     0.0     0.0
7             0.0        0.0           0.0     0.0     NaN
8             0.0      785.0          17.0   216.0     0.0
9             0.0        0.0           0.0     0.0     0.0
10            0.0        0.0           NaN     0.0     0.0
11           39.0     7295.0         589.0   110.0   124.0
12           73.0        0.0        1123.0     0.0   113.0
13          719.0        1.0          65.0     0.0    24.0
14            8.0      974.0          12.0     2.0     7.0
15           32.0        0.0         876.0     0.0     0.0
16         1286.0      122.0           NaN     0.0     0.0
17            0.0        1.0           0.0     0.0   637.0
18            0.0        0.0           0.0     0.0     0.0
19            0.0        0.0           0.0     0.0     0.0
20          412.0        0.0           1.0     0.0   679.0
21            0.0        0.0           0.0     0.0     0.0
22            0.0        0.0           0.0     0.0     0.0
23            0.0        0.0           NaN     0.0     0.0
24            0.0        0.0           0.0     0.0     0.0
25            NaN        0.0           0.0     0.0     0.0
26            0.0        0.0           0.0     0.0     0.0
27          980.0        2.0          69.0     0.0     0.0
28            0.0        0.0           NaN     0.0     0.0
29            0.0      225.0           0.0   998.0     0.0
...           ...        ...           ...     ...     ...
8663          0.0        0.0           0.0     0.0     0.0
8664          0.0        0.0           0.0     0.0     0.0
8665          0.0        0.0           0.0     0.0     NaN
8666         28.0     1208.0         973.0   207.0     0.0
8667          0.0     2972.0           NaN    28.0   188.0
8668          0.0        0.0           0.0     0.0     0.0
8669          0.0     8160.0         205.0     0.0   438.0
8670          0.0        0.0           0.0     0.0     0.0
8671          0.0        0.0           0.0     0.0     0.0
8672          0.0        0.0           0.0     0.0     0.0
8673          0.0        0.0           0.0     0.0     0.0
8674         39.0        0.0        1085.0    24.0     0.0
8675       1030.0     1015.0           0.0    11.0     NaN
8676          0.0        0.0           0.0     0.0     0.0
8677          0.0        0.0           0.0     0.0     0.0
8678          0.0        0.0           0.0     0.0     0.0
8679          0.0        0.0           0.0     0.0     0.0
8680          0.0        0.0           0.0     0.0     0.0
8681          0.0        0.0           0.0     0.0     0.0
8682        240.0      242.0         510.0     0.0     0.0
8683         86.0        3.0         149.0   208.0   329.0
8684          0.0        0.0           0.0     0.0     0.0
8685          0.0        0.0           0.0     0.0     0.0
8686          1.0     1146.0           0.0    50.0    34.0
8687          0.0     3208.0           0.0     2.0   330.0
8688          0.0     6819.0           0.0  1643.0    74.0
8689          0.0        0.0           0.0     0.0     0.0
8690          0.0        0.0        1872.0     1.0     0.0
8691          0.0     1049.0           0.0   353.0  3235.0
8692        126.0     4688.0           0.0     0.0    12.0

                    Name  Transported
0        Maham Ofracculy        False
1           Juanna Vines         True
2          Altark Susent        False
3           Solam Susent        False
4      Willy Santantines         True
5      Sandie Hinetthews         True
6     Billex Jacostaffey         True
7     Candra Jacostaffey         True
8          Andona Beston         True
9         Erraiam Flatic         True
10        Altardr Flatic         True
11         Wezena Flatic         True
12          Berers Barne         True
13        Reney Baketton        False
14       Elle Bertsontry         True
15         Justie Pooles        False
16           Flats Eccle        False
17       Carry Hughriend        False
18            Alus Upead         True
19         Lyde Brighttt         True
20       Philda Brighttt        False
21     Almary Brantuarez        False
22     Glendy Brantuarez        False
23    Mollen Mcfaddennon        False
24    Breney Jacostanley         True
25       Mael Brantuarez        False
26     Terta Mcfaddennon        False
27                   NaN        False
28       Penton Fullided         True
29     Karard Brookenson        False
...                  ...          ...
8663     Chrisa Francock         True
8664                 NaN         True
8665         Phia Cleang        False
8666          Gian Perle         True
8667    Chain Reedectied         True
8668        Melios Kashe         True
8669  Alchium Stranbeate         True
8670   Muonon Stranbeate         True
8671     Jimmyn Thomason         True
8672      Kenny Mallerez        False
8673      Darley Franton         True
8674          Ties Apple        False
8675     Annah Gilleyons         True
8676     Therta Casentry        False
8677   Giedir Sionerorly         True
8678      Arraid Opshaft         True
8679        Sabi Opshaft         True
8680      Agnesa Baldson         True
8681       Lan Mckinsond         True
8682       Ireene Simson         True
8683        Gordo Simson        False
8684     Chelsa Bullisey         True
8685     Polaton Conable         True
8686       Diram Conable        False
8687     Atlasym Conable         True
8688   Gravior Noxnuther        False
8689     Kurta Mondalley        False
8690        Fayey Connon         True
8691    Celeon Hontichre        False
8692    Propsh Hontichre         True

[8693 rows x 14 columns]

In [94]:
d.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [95]:
d.shape

(8693, 14)

In [96]:
type(d)

pandas.core.frame.DataFrame

In [97]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
PassengerId     8693 non-null object
HomePlanet      8492 non-null object
CryoSleep       8476 non-null object
Cabin           8494 non-null object
Destination     8511 non-null object
Age             8514 non-null float64
VIP             8490 non-null object
RoomService     8512 non-null float64
FoodCourt       8510 non-null float64
ShoppingMall    8485 non-null float64
Spa             8510 non-null float64
VRDeck          8505 non-null float64
Name            8493 non-null object
Transported     8693 non-null bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [98]:
d.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name', 'Transported'],
      dtype='object')

In [99]:
d.isnull()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,True,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,True,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,True,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,True,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,True,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,True,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False,True,False
28,False,False,False,False,False,False,False,False,False,True,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8663,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8664,False,False,True,False,False,False,False,False,False,False,False,False,True,False
8665,False,False,False,False,False,False,False,False,False,False,False,True,False,False
8666,False,True,False,False,False,False,True,False,False,False,False,False,False,False
8667,False,False,False,False,False,False,False,False,False,True,False,False,False,False
8668,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8669,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8670,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8671,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8672,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8673,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8674,False,True,False,False,False,False,False,False,False,False,False,False,False,False
8675,False,False,True,False,False,False,False,False,False,False,False,True,False,False
8676,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8677,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8678,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8679,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8680,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8681,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8682,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8683,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8684,False,True,False,False,False,False,False,False,False,False,False,False,False,False
8685,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8686,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8687,False,False,True,False,False,False,False,False,False,False,False,False,False,False
8688,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8689,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8690,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8691,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8692,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [100]:
d.isnull

<bound method DataFrame.isnull of      PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False
5        0005_01      Earth     False     F/0/P  PSO J318.5-22  44.0  False
6        0006_01      Earth     False     F/2/S    TRAPPIST-1e  26.0  False
7        0006_02      Earth      True     G/0/S    TRAPPIST-1e  28.0  False
8        0007_01      Earth     False     F/3/S    TRAPPIST-1e  35.0  False
9        0008_01     Europa      True     B/1/P    55 Cancri e  14.0  False
10       0008_02     Europa      True     B/1/P    TRAPPIST-1e  34.0  False
11       0008_03     Europa     False     B/1/P    55 Cancri e  45.0  False
12       0009_01       Mars     False     F/1/P    TRAPPIST-1e  32.0  False
13       0010_01      Earth     False     G/1/S    TRAPPIST-1e  48.0  False
14       0011_01      Earth     False     F/2/P    TRAPPIST-1e  28.0  False
15       0012_01      Earth     False       NaN    TRAPPIST-1e  31.0  False
16       0014_01       Mars     False     F/3/P    55 Cancri e  27.0  False
17       0015_01      Earth     False     F/4/P    55 Cancri e  24.0  False
18       0016_01       Mars      True     F/5/P    TRAPPIST-1e  45.0  False
19       0017_01      Earth     False     G/0/P    TRAPPIST-1e   0.0  False
20       0017_02      Earth     False     F/6/P    55 Cancri e  14.0  False
21       0020_01      Earth      True     E/0/S    TRAPPIST-1e   1.0  False
22       0020_02      Earth      True     E/0/S    55 Cancri e  49.0  False
23       0020_03      Earth      True     E/0/S    55 Cancri e  29.0  False
24       0020_04      Earth     False     E/0/S    TRAPPIST-1e  10.0  False
25       0020_05      Earth      True     E/0/S  PSO J318.5-22   1.0  False
26       0020_06      Earth     False     E/0/S    TRAPPIST-1e   7.0  False
27       0022_01       Mars     False     D/0/P    TRAPPIST-1e  21.0  False
28       0024_01     Europa      True     C/2/S    TRAPPIST-1e  62.0  False
29       0025_01      Earth     False     F/6/S    TRAPPIST-1e  15.0  False
...          ...        ...       ...       ...            ...   ...    ...
8663     9244_01      Earth      True  G/1489/S  PSO J318.5-22  13.0  False
8664     9246_01      Earth       NaN  G/1490/S    TRAPPIST-1e  32.0  False
8665     9247_01      Earth      True  G/1491/S    TRAPPIST-1e  33.0  False
8666     9248_01        NaN     False  F/1792/S    55 Cancri e  38.0    NaN
8667     9250_01     Europa     False   E/597/P    TRAPPIST-1e  29.0  False
8668     9251_01       Mars      True  F/1793/S    TRAPPIST-1e  25.0  False
8669     9252_01     Europa     False   B/301/P    55 Cancri e  26.0  False
8670     9252_02     Europa      True   B/301/P    55 Cancri e  19.0  False
8671     9253_01      Earth      True  G/1493/S  PSO J318.5-22  16.0  False
8672     9254_01      Earth      True  G/1502/P  PSO J318.5-22  61.0  False
8673     9256_01      Earth      True  G/1494/S    TRAPPIST-1e  28.0  False
8674     9257_01        NaN     False  F/1892/P    TRAPPIST-1e  13.0  False
8675     9259_01      Earth       NaN  F/1893/P    TRAPPIST-1e  44.0  False
8676     9261_01      Earth      True  G/1504/P  PSO J318.5-22  22.0  False
8677     9264_01     Europa      True   E/606/S    55 Cancri e  30.0  False
8678     9267_01     Europa      True   E/607/S    TRAPPIST-1e  21.0  False
8679     9267_02     Europa      True   E/607/S    TRAPPIST-1e  20.0  False
8680     9268_01      Earth      True  G/1505/P    TRAPPIST-1e  31.0  False
8681     9270_01      Earth      True  G/1497/S    55 Cancri e  33.0  False
8682     9272_01      Earth     False  G/1507/P    TRAPPIST-1e  26.0  False
8683     9272_02      Earth     False  F/1894/P    TRAPPIST-1e  21.0  False
8684     9274_01        NaN      True  G/1508/P    TRAPPIST-1e  23.0  False
8685     9275_01     Europa     False    A/97/P    TRAPPIST-1e   0.0  False
8686     9275_02     Europa     False    A/97/P    TRAPPIST-1e  32.0  False
8687     9275_03     Europa       NaN    A/97/P    TRAPPIST-1e  30.0  False
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  \
0             0.0        0.0           0.0     0.0     0.0
1           109.0        9.0          25.0   549.0    44.0
2            43.0     3576.0           0.0  6715.0    49.0
3             0.0     1283.0         371.0  3329.0   193.0
4           303.0       70.0         151.0   565.0     2.0
5             0.0      483.0           0.0   291.0     0.0
6            42.0     1539.0           3.0     0.0     0.0
7             0.0        0.0           0.0     0.0     NaN
8             0.0      785.0          17.0   216.0     0.0
9             0.0        0.0           0.0     0.0     0.0
10            0.0        0.0           NaN     0.0     0.0
11           39.0     7295.0         589.0   110.0   124.0
12           73.0        0.0        1123.0     0.0   113.0
13          719.0        1.0          65.0     0.0    24.0
14            8.0      974.0          12.0     2.0     7.0
15           32.0        0.0         876.0     0.0     0.0
16         1286.0      122.0           NaN     0.0     0.0
17            0.0        1.0           0.0     0.0   637.0
18            0.0        0.0           0.0     0.0     0.0
19            0.0        0.0           0.0     0.0     0.0
20          412.0        0.0           1.0     0.0   679.0
21            0.0        0.0           0.0     0.0     0.0
22            0.0        0.0           0.0     0.0     0.0
23            0.0        0.0           NaN     0.0     0.0
24            0.0        0.0           0.0     0.0     0.0
25            NaN        0.0           0.0     0.0     0.0
26            0.0        0.0           0.0     0.0     0.0
27          980.0        2.0          69.0     0.0     0.0
28            0.0        0.0           NaN     0.0     0.0
29            0.0      225.0           0.0   998.0     0.0
...           ...        ...           ...     ...     ...
8663          0.0        0.0           0.0     0.0     0.0
8664          0.0        0.0           0.0     0.0     0.0
8665          0.0        0.0           0.0     0.0     NaN
8666         28.0     1208.0         973.0   207.0     0.0
8667          0.0     2972.0           NaN    28.0   188.0
8668          0.0        0.0           0.0     0.0     0.0
8669          0.0     8160.0         205.0     0.0   438.0
8670          0.0        0.0           0.0     0.0     0.0
8671          0.0        0.0           0.0     0.0     0.0
8672          0.0        0.0           0.0     0.0     0.0
8673          0.0        0.0           0.0     0.0     0.0
8674         39.0        0.0        1085.0    24.0     0.0
8675       1030.0     1015.0           0.0    11.0     NaN
8676          0.0        0.0           0.0     0.0     0.0
8677          0.0        0.0           0.0     0.0     0.0
8678          0.0        0.0           0.0     0.0     0.0
8679          0.0        0.0           0.0     0.0     0.0
8680          0.0        0.0           0.0     0.0     0.0
8681          0.0        0.0           0.0     0.0     0.0
8682        240.0      242.0         510.0     0.0     0.0
8683         86.0        3.0         149.0   208.0   329.0
8684          0.0        0.0           0.0     0.0     0.0
8685          0.0        0.0           0.0     0.0     0.0
8686          1.0     1146.0           0.0    50.0    34.0
8687          0.0     3208.0           0.0     2.0   330.0
8688          0.0     6819.0           0.0  1643.0    74.0
8689          0.0        0.0           0.0     0.0     0.0
8690          0.0        0.0        1872.0     1.0     0.0
8691          0.0     1049.0           0.0   353.0  3235.0
8692        126.0     4688.0           0.0     0.0    12.0

                    Name  Transported
0        Maham Ofracculy        False
1           Juanna Vines         True
2          Altark Susent        False
3           Solam Susent        False
4      Willy Santantines         True
5      Sandie Hinetthews         True
6     Billex Jacostaffey         True
7     Candra Jacostaffey         True
8          Andona Beston         True
9         Erraiam Flatic         True
10        Altardr Flatic         True
11         Wezena Flatic         True
12          Berers Barne         True
13        Reney Baketton        False
14       Elle Bertsontry         True
15         Justie Pooles        False
16           Flats Eccle        False
17       Carry Hughriend        False
18            Alus Upead         True
19         Lyde Brighttt         True
20       Philda Brighttt        False
21     Almary Brantuarez        False
22     Glendy Brantuarez        False
23    Mollen Mcfaddennon        False
24    Breney Jacostanley         True
25       Mael Brantuarez        False
26     Terta Mcfaddennon        False
27                   NaN        False
28       Penton Fullided         True
29     Karard Brookenson        False
...                  ...          ...
8663     Chrisa Francock         True
8664                 NaN         True
8665         Phia Cleang        False
8666          Gian Perle         True
8667    Chain Reedectied         True
8668        Melios Kashe         True
8669  Alchium Stranbeate         True
8670   Muonon Stranbeate         True
8671     Jimmyn Thomason         True
8672      Kenny Mallerez        False
8673      Darley Franton         True
8674          Ties Apple        False
8675     Annah Gilleyons         True
8676     Therta Casentry        False
8677   Giedir Sionerorly         True
8678      Arraid Opshaft         True
8679        Sabi Opshaft         True
8680      Agnesa Baldson         True
8681       Lan Mckinsond         True
8682       Ireene Simson         True
8683        Gordo Simson        False
8684     Chelsa Bullisey         True
8685     Polaton Conable         True
8686       Diram Conable        False
8687     Atlasym Conable         True
8688   Gravior Noxnuther        False
8689     Kurta Mondalley        False
8690        Fayey Connon         True
8691    Celeon Hontichre        False
8692    Propsh Hontichre         True

[8693 rows x 14 columns]>

In [101]:
d.shape[1]

14

In [102]:
d['HomePlanet'].value_counts
print(d)

     PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False
5        0005_01      Earth     False     F/0/P  PSO J318.5-22  44.0  False
6        0006_01      Earth     False     F/2/S    TRAPPIST-1e  26.0  False
7        0006_02      Earth      True     G/0/S    TRAPPIST-1e  28.0  False
8        0007_01      Earth     False     F/3/S    TRAPPIST-1e  35.0  False
9        0008_01     Europa      True     B/1/P    55 Cancri e  14.0  False
10       0008_02     Europa      True     B/1/P    TRAPPIST-1e  34.0  False
11       0008_03     Europa     False     B/1/P    55 Cancri e  45.0  False
12       0009_01       Mars     False     F/1/P    TRAPPIST-1e  32.0  False
13       0010_01      Earth     False     G/1/S    TRAPPIST-1e  48.0  False
14       0011_01      Earth     False     F/2/P    TRAPPIST-1e  28.0  False
15       0012_01      Earth     False       NaN    TRAPPIST-1e  31.0  False
16       0014_01       Mars     False     F/3/P    55 Cancri e  27.0  False
17       0015_01      Earth     False     F/4/P    55 Cancri e  24.0  False
18       0016_01       Mars      True     F/5/P    TRAPPIST-1e  45.0  False
19       0017_01      Earth     False     G/0/P    TRAPPIST-1e   0.0  False
20       0017_02      Earth     False     F/6/P    55 Cancri e  14.0  False
21       0020_01      Earth      True     E/0/S    TRAPPIST-1e   1.0  False
22       0020_02      Earth      True     E/0/S    55 Cancri e  49.0  False
23       0020_03      Earth      True     E/0/S    55 Cancri e  29.0  False
24       0020_04      Earth     False     E/0/S    TRAPPIST-1e  10.0  False
25       0020_05      Earth      True     E/0/S  PSO J318.5-22   1.0  False
26       0020_06      Earth     False     E/0/S    TRAPPIST-1e   7.0  False
27       0022_01       Mars     False     D/0/P    TRAPPIST-1e  21.0  False
28       0024_01     Europa      True     C/2/S    TRAPPIST-1e  62.0  False
29       0025_01      Earth     False     F/6/S    TRAPPIST-1e  15.0  False
...          ...        ...       ...       ...            ...   ...    ...
8663     9244_01      Earth      True  G/1489/S  PSO J318.5-22  13.0  False
8664     9246_01      Earth       NaN  G/1490/S    TRAPPIST-1e  32.0  False
8665     9247_01      Earth      True  G/1491/S    TRAPPIST-1e  33.0  False
8666     9248_01        NaN     False  F/1792/S    55 Cancri e  38.0    NaN
8667     9250_01     Europa     False   E/597/P    TRAPPIST-1e  29.0  False
8668     9251_01       Mars      True  F/1793/S    TRAPPIST-1e  25.0  False
8669     9252_01     Europa     False   B/301/P    55 Cancri e  26.0  False
8670     9252_02     Europa      True   B/301/P    55 Cancri e  19.0  False
8671     9253_01      Earth      True  G/1493/S  PSO J318.5-22  16.0  False
8672     9254_01      Earth      True  G/1502/P  PSO J318.5-22  61.0  False
8673     9256_01      Earth      True  G/1494/S    TRAPPIST-1e  28.0  False
8674     9257_01        NaN     False  F/1892/P    TRAPPIST-1e  13.0  False
8675     9259_01      Earth       NaN  F/1893/P    TRAPPIST-1e  44.0  False
8676     9261_01      Earth      True  G/1504/P  PSO J318.5-22  22.0  False
8677     9264_01     Europa      True   E/606/S    55 Cancri e  30.0  False
8678     9267_01     Europa      True   E/607/S    TRAPPIST-1e  21.0  False
8679     9267_02     Europa      True   E/607/S    TRAPPIST-1e  20.0  False
8680     9268_01      Earth      True  G/1505/P    TRAPPIST-1e  31.0  False
8681     9270_01      Earth      True  G/1497/S    55 Cancri e  33.0  False
8682     9272_01      Earth     False  G/1507/P    TRAPPIST-1e  26.0  False
8683     9272_02      Earth     False  F/1894/P    TRAPPIST-1e  21.0  False
8684     9274_01        NaN      True  G/1508/P    TRAPPIST-1e  23.0  False
8685     9275_01     Europa     False    A/97/P    TRAPPIST-1e   0.0  False
8686     9275_02     Europa     False    A/97/P    TRAPPIST-1e  32.0  False
8687     9275_03     Europa       NaN    A/97/P    TRAPPIST-1e  30.0  False
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck  \
0             0.0        0.0           0.0     0.0     0.0
1           109.0        9.0          25.0   549.0    44.0
2            43.0     3576.0           0.0  6715.0    49.0
3             0.0     1283.0         371.0  3329.0   193.0
4           303.0       70.0         151.0   565.0     2.0
5             0.0      483.0           0.0   291.0     0.0
6            42.0     1539.0           3.0     0.0     0.0
7             0.0        0.0           0.0     0.0     NaN
8             0.0      785.0          17.0   216.0     0.0
9             0.0        0.0           0.0     0.0     0.0
10            0.0        0.0           NaN     0.0     0.0
11           39.0     7295.0         589.0   110.0   124.0
12           73.0        0.0        1123.0     0.0   113.0
13          719.0        1.0          65.0     0.0    24.0
14            8.0      974.0          12.0     2.0     7.0
15           32.0        0.0         876.0     0.0     0.0
16         1286.0      122.0           NaN     0.0     0.0
17            0.0        1.0           0.0     0.0   637.0
18            0.0        0.0           0.0     0.0     0.0
19            0.0        0.0           0.0     0.0     0.0
20          412.0        0.0           1.0     0.0   679.0
21            0.0        0.0           0.0     0.0     0.0
22            0.0        0.0           0.0     0.0     0.0
23            0.0        0.0           NaN     0.0     0.0
24            0.0        0.0           0.0     0.0     0.0
25            NaN        0.0           0.0     0.0     0.0
26            0.0        0.0           0.0     0.0     0.0
27          980.0        2.0          69.0     0.0     0.0
28            0.0        0.0           NaN     0.0     0.0
29            0.0      225.0           0.0   998.0     0.0
...           ...        ...           ...     ...     ...
8663          0.0        0.0           0.0     0.0     0.0
8664          0.0        0.0           0.0     0.0     0.0
8665          0.0        0.0           0.0     0.0     NaN
8666         28.0     1208.0         973.0   207.0     0.0
8667          0.0     2972.0           NaN    28.0   188.0
8668          0.0        0.0           0.0     0.0     0.0
8669          0.0     8160.0         205.0     0.0   438.0
8670          0.0        0.0           0.0     0.0     0.0
8671          0.0        0.0           0.0     0.0     0.0
8672          0.0        0.0           0.0     0.0     0.0
8673          0.0        0.0           0.0     0.0     0.0
8674         39.0        0.0        1085.0    24.0     0.0
8675       1030.0     1015.0           0.0    11.0     NaN
8676          0.0        0.0           0.0     0.0     0.0
8677          0.0        0.0           0.0     0.0     0.0
8678          0.0        0.0           0.0     0.0     0.0
8679          0.0        0.0           0.0     0.0     0.0
8680          0.0        0.0           0.0     0.0     0.0
8681          0.0        0.0           0.0     0.0     0.0
8682        240.0      242.0         510.0     0.0     0.0
8683         86.0        3.0         149.0   208.0   329.0
8684          0.0        0.0           0.0     0.0     0.0
8685          0.0        0.0           0.0     0.0     0.0
8686          1.0     1146.0           0.0    50.0    34.0
8687          0.0     3208.0           0.0     2.0   330.0
8688          0.0     6819.0           0.0  1643.0    74.0
8689          0.0        0.0           0.0     0.0     0.0
8690          0.0        0.0        1872.0     1.0     0.0
8691          0.0     1049.0           0.0   353.0  3235.0
8692        126.0     4688.0           0.0     0.0    12.0

                    Name  Transported
0        Maham Ofracculy        False
1           Juanna Vines         True
2          Altark Susent        False
3           Solam Susent        False
4      Willy Santantines         True
5      Sandie Hinetthews         True
6     Billex Jacostaffey         True
7     Candra Jacostaffey         True
8          Andona Beston         True
9         Erraiam Flatic         True
10        Altardr Flatic         True
11         Wezena Flatic         True
12          Berers Barne         True
13        Reney Baketton        False
14       Elle Bertsontry         True
15         Justie Pooles        False
16           Flats Eccle        False
17       Carry Hughriend        False
18            Alus Upead         True
19         Lyde Brighttt         True
20       Philda Brighttt        False
21     Almary Brantuarez        False
22     Glendy Brantuarez        False
23    Mollen Mcfaddennon        False
24    Breney Jacostanley         True
25       Mael Brantuarez        False
26     Terta Mcfaddennon        False
27                   NaN        False
28       Penton Fullided         True
29     Karard Brookenson        False
...                  ...          ...
8663     Chrisa Francock         True
8664                 NaN         True
8665         Phia Cleang        False
8666          Gian Perle         True
8667    Chain Reedectied         True
8668        Melios Kashe         True
8669  Alchium Stranbeate         True
8670   Muonon Stranbeate         True
8671     Jimmyn Thomason         True
8672      Kenny Mallerez        False
8673      Darley Franton         True
8674          Ties Apple        False
8675     Annah Gilleyons         True
8676     Therta Casentry        False
8677   Giedir Sionerorly         True
8678      Arraid Opshaft         True
8679        Sabi Opshaft         True
8680      Agnesa Baldson         True
8681       Lan Mckinsond         True
8682       Ireene Simson         True
8683        Gordo Simson        False
8684     Chelsa Bullisey         True
8685     Polaton Conable         True
8686       Diram Conable        False
8687     Atlasym Conable         True
8688   Gravior Noxnuther        False
8689     Kurta Mondalley        False
8690        Fayey Connon         True
8691    Celeon Hontichre        False
8692    Propsh Hontichre         True

[8693 rows x 14 columns]

In [103]:
df3=d.drop(['Transported'],axis=1)
print(df3)

     PassengerId HomePlanet CryoSleep     Cabin    Destination   Age    VIP  \
0        0001_01     Europa     False     B/0/P    TRAPPIST-1e  39.0  False
1        0002_01      Earth     False     F/0/S    TRAPPIST-1e  24.0  False
2        0003_01     Europa     False     A/0/S    TRAPPIST-1e  58.0   True
3        0003_02     Europa     False     A/0/S    TRAPPIST-1e  33.0  False
4        0004_01      Earth     False     F/1/S    TRAPPIST-1e  16.0  False
5        0005_01      Earth     False     F/0/P  PSO J318.5-22  44.0  False
6        0006_01      Earth     False     F/2/S    TRAPPIST-1e  26.0  False
7        0006_02      Earth      True     G/0/S    TRAPPIST-1e  28.0  False
8        0007_01      Earth     False     F/3/S    TRAPPIST-1e  35.0  False
9        0008_01     Europa      True     B/1/P    55 Cancri e  14.0  False
10       0008_02     Europa      True     B/1/P    TRAPPIST-1e  34.0  False
11       0008_03     Europa     False     B/1/P    55 Cancri e  45.0  False
12       0009_01       Mars     False     F/1/P    TRAPPIST-1e  32.0  False
13       0010_01      Earth     False     G/1/S    TRAPPIST-1e  48.0  False
14       0011_01      Earth     False     F/2/P    TRAPPIST-1e  28.0  False
15       0012_01      Earth     False       NaN    TRAPPIST-1e  31.0  False
16       0014_01       Mars     False     F/3/P    55 Cancri e  27.0  False
17       0015_01      Earth     False     F/4/P    55 Cancri e  24.0  False
18       0016_01       Mars      True     F/5/P    TRAPPIST-1e  45.0  False
19       0017_01      Earth     False     G/0/P    TRAPPIST-1e   0.0  False
20       0017_02      Earth     False     F/6/P    55 Cancri e  14.0  False
21       0020_01      Earth      True     E/0/S    TRAPPIST-1e   1.0  False
22       0020_02      Earth      True     E/0/S    55 Cancri e  49.0  False
23       0020_03      Earth      True     E/0/S    55 Cancri e  29.0  False
24       0020_04      Earth     False     E/0/S    TRAPPIST-1e  10.0  False
25       0020_05      Earth      True     E/0/S  PSO J318.5-22   1.0  False
26       0020_06      Earth     False     E/0/S    TRAPPIST-1e   7.0  False
27       0022_01       Mars     False     D/0/P    TRAPPIST-1e  21.0  False
28       0024_01     Europa      True     C/2/S    TRAPPIST-1e  62.0  False
29       0025_01      Earth     False     F/6/S    TRAPPIST-1e  15.0  False
...          ...        ...       ...       ...            ...   ...    ...
8663     9244_01      Earth      True  G/1489/S  PSO J318.5-22  13.0  False
8664     9246_01      Earth       NaN  G/1490/S    TRAPPIST-1e  32.0  False
8665     9247_01      Earth      True  G/1491/S    TRAPPIST-1e  33.0  False
8666     9248_01        NaN     False  F/1792/S    55 Cancri e  38.0    NaN
8667     9250_01     Europa     False   E/597/P    TRAPPIST-1e  29.0  False
8668     9251_01       Mars      True  F/1793/S    TRAPPIST-1e  25.0  False
8669     9252_01     Europa     False   B/301/P    55 Cancri e  26.0  False
8670     9252_02     Europa      True   B/301/P    55 Cancri e  19.0  False
8671     9253_01      Earth      True  G/1493/S  PSO J318.5-22  16.0  False
8672     9254_01      Earth      True  G/1502/P  PSO J318.5-22  61.0  False
8673     9256_01      Earth      True  G/1494/S    TRAPPIST-1e  28.0  False
8674     9257_01        NaN     False  F/1892/P    TRAPPIST-1e  13.0  False
8675     9259_01      Earth       NaN  F/1893/P    TRAPPIST-1e  44.0  False
8676     9261_01      Earth      True  G/1504/P  PSO J318.5-22  22.0  False
8677     9264_01     Europa      True   E/606/S    55 Cancri e  30.0  False
8678     9267_01     Europa      True   E/607/S    TRAPPIST-1e  21.0  False
8679     9267_02     Europa      True   E/607/S    TRAPPIST-1e  20.0  False
8680     9268_01      Earth      True  G/1505/P    TRAPPIST-1e  31.0  False
8681     9270_01      Earth      True  G/1497/S    55 Cancri e  33.0  False
8682     9272_01      Earth     False  G/1507/P    TRAPPIST-1e  26.0  False
8683     9272_02      Earth     False  F/1894/P    TRAPPIST-1e  21.0  False
8684     9274_01        NaN      True  G/1508/P    TRAPPIST-1e  23.0  False
8685     9275_01     Europa     False    A/97/P    TRAPPIST-1e   0.0  False
8686     9275_02     Europa     False    A/97/P    TRAPPIST-1e  32.0  False
8687     9275_03     Europa       NaN    A/97/P    TRAPPIST-1e  30.0  False
8688     9276_01     Europa     False    A/98/P    55 Cancri e  41.0   True
8689     9278_01      Earth      True  G/1499/S  PSO J318.5-22  18.0  False
8690     9279_01      Earth     False  G/1500/S    TRAPPIST-1e  26.0  False
8691     9280_01     Europa     False   E/608/S    55 Cancri e  32.0  False
8692     9280_02     Europa     False   E/608/S    TRAPPIST-1e  44.0  False

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck                Name
0             0.0        0.0           0.0     0.0     0.0     Maham Ofracculy
1           109.0        9.0          25.0   549.0    44.0        Juanna Vines
2            43.0     3576.0           0.0  6715.0    49.0       Altark Susent
3             0.0     1283.0         371.0  3329.0   193.0        Solam Susent
4           303.0       70.0         151.0   565.0     2.0   Willy Santantines
5             0.0      483.0           0.0   291.0     0.0   Sandie Hinetthews
6            42.0     1539.0           3.0     0.0     0.0  Billex Jacostaffey
7             0.0        0.0           0.0     0.0     NaN  Candra Jacostaffey
8             0.0      785.0          17.0   216.0     0.0       Andona Beston
9             0.0        0.0           0.0     0.0     0.0      Erraiam Flatic
10            0.0        0.0           NaN     0.0     0.0      Altardr Flatic
11           39.0     7295.0         589.0   110.0   124.0       Wezena Flatic
12           73.0        0.0        1123.0     0.0   113.0        Berers Barne
13          719.0        1.0          65.0     0.0    24.0      Reney Baketton
14            8.0      974.0          12.0     2.0     7.0     Elle Bertsontry
15           32.0        0.0         876.0     0.0     0.0       Justie Pooles
16         1286.0      122.0           NaN     0.0     0.0         Flats Eccle
17            0.0        1.0           0.0     0.0   637.0     Carry Hughriend
18            0.0        0.0           0.0     0.0     0.0          Alus Upead
19            0.0        0.0           0.0     0.0     0.0       Lyde Brighttt
20          412.0        0.0           1.0     0.0   679.0     Philda Brighttt
21            0.0        0.0           0.0     0.0     0.0   Almary Brantuarez
22            0.0        0.0           0.0     0.0     0.0   Glendy Brantuarez
23            0.0        0.0           NaN     0.0     0.0  Mollen Mcfaddennon
24            0.0        0.0           0.0     0.0     0.0  Breney Jacostanley
25            NaN        0.0           0.0     0.0     0.0     Mael Brantuarez
26            0.0        0.0           0.0     0.0     0.0   Terta Mcfaddennon
27          980.0        2.0          69.0     0.0     0.0                 NaN
28            0.0        0.0           NaN     0.0     0.0     Penton Fullided
29            0.0      225.0           0.0   998.0     0.0   Karard Brookenson
...           ...        ...           ...     ...     ...                 ...
8663          0.0        0.0           0.0     0.0     0.0     Chrisa Francock
8664          0.0        0.0           0.0     0.0     0.0                 NaN
8665          0.0        0.0           0.0     0.0     NaN         Phia Cleang
8666         28.0     1208.0         973.0   207.0     0.0          Gian Perle
8667          0.0     2972.0           NaN    28.0   188.0    Chain Reedectied
8668          0.0        0.0           0.0     0.0     0.0        Melios Kashe
8669          0.0     8160.0         205.0     0.0   438.0  Alchium Stranbeate
8670          0.0        0.0           0.0     0.0     0.0   Muonon Stranbeate
8671          0.0        0.0           0.0     0.0     0.0     Jimmyn Thomason
8672          0.0        0.0           0.0     0.0     0.0      Kenny Mallerez
8673          0.0        0.0           0.0     0.0     0.0      Darley Franton
8674         39.0        0.0        1085.0    24.0     0.0          Ties Apple
8675       1030.0     1015.0           0.0    11.0     NaN     Annah Gilleyons
8676          0.0        0.0           0.0     0.0     0.0     Therta Casentry
8677          0.0        0.0           0.0     0.0     0.0   Giedir Sionerorly
8678          0.0        0.0           0.0     0.0     0.0      Arraid Opshaft
8679          0.0        0.0           0.0     0.0     0.0        Sabi Opshaft
8680          0.0        0.0           0.0     0.0     0.0      Agnesa Baldson
8681          0.0        0.0           0.0     0.0     0.0       Lan Mckinsond
8682        240.0      242.0         510.0     0.0     0.0       Ireene Simson
8683         86.0        3.0         149.0   208.0   329.0        Gordo Simson
8684          0.0        0.0           0.0     0.0     0.0     Chelsa Bullisey
8685          0.0        0.0           0.0     0.0     0.0     Polaton Conable
8686          1.0     1146.0           0.0    50.0    34.0       Diram Conable
8687          0.0     3208.0           0.0     2.0   330.0     Atlasym Conable
8688          0.0     6819.0           0.0  1643.0    74.0   Gravior Noxnuther
8689          0.0        0.0           0.0     0.0     0.0     Kurta Mondalley
8690          0.0        0.0        1872.0     1.0     0.0        Fayey Connon
8691          0.0     1049.0           0.0   353.0  3235.0    Celeon Hontichre
8692        126.0     4688.0           0.0     0.0    12.0    Propsh Hontichre

[8693 rows x 13 columns]

In [104]:
x=pd.DataFrame(d['FoodCourt'])

In [105]:
y=pd.DataFrame(d['RoomService'])

In [106]:
x

      FoodCourt
0           0.0
1           9.0
2        3576.0
3        1283.0
4          70.0
5         483.0
6        1539.0
7           0.0
8         785.0
9           0.0
10          0.0
11       7295.0
12          0.0
13          1.0
14        974.0
15          0.0
16        122.0
17          1.0
18          0.0
19          0.0
20          0.0
21          0.0
22          0.0
23          0.0
24          0.0
25          0.0
26          0.0
27          2.0
28          0.0
29        225.0
...         ...
8663        0.0
8664        0.0
8665        0.0
8666     1208.0
8667     2972.0
8668        0.0
8669     8160.0
8670        0.0
8671        0.0
8672        0.0
8673        0.0
8674        0.0
8675     1015.0
8676        0.0
8677        0.0
8678        0.0
8679        0.0
8680        0.0
8681        0.0
8682      242.0
8683        3.0
8684        0.0
8685        0.0
8686     1146.0
8687     3208.0
8688     6819.0
8689        0.0
8690        0.0
8691     1049.0
8692     4688.0

[8693 rows x 1 columns]

In [107]:
y

      RoomService
0             0.0
1           109.0
2            43.0
3             0.0
4           303.0
5             0.0
6            42.0
7             0.0
8             0.0
9             0.0
10            0.0
11           39.0
12           73.0
13          719.0
14            8.0
15           32.0
16         1286.0
17            0.0
18            0.0
19            0.0
20          412.0
21            0.0
22            0.0
23            0.0
24            0.0
25            NaN
26            0.0
27          980.0
28            0.0
29            0.0
...           ...
8663          0.0
8664          0.0
8665          0.0
8666         28.0
8667          0.0
8668          0.0
8669          0.0
8670          0.0
8671          0.0
8672          0.0
8673          0.0
8674         39.0
8675       1030.0
8676          0.0
8677          0.0
8678          0.0
8679          0.0
8680          0.0
8681          0.0
8682        240.0
8683         86.0
8684          0.0
8685          0.0
8686          1.0
8687          0.0
8688          0.0
8689          0.0
8690          0.0
8691          0.0
8692        126.0

[8693 rows x 1 columns]

In [108]:
type(x)

pandas.core.frame.DataFrame

In [109]:
type(y)

pandas.core.frame.DataFrame

In [110]:
x = d.iloc[:, :-1].values 
print(x)

[['0001_01' 'Europa' False ... 0.0 0.0 'Maham Ofracculy']
 ['0002_01' 'Earth' False ... 549.0 44.0 'Juanna Vines']
 ['0003_01' 'Europa' False ... 6715.0 49.0 'Altark Susent']
 ...
 ['9279_01' 'Earth' False ... 1.0 0.0 'Fayey Connon']
 ['9280_01' 'Europa' False ... 353.0 3235.0 'Celeon Hontichre']
 ['9280_02' 'Europa' False ... 0.0 12.0 'Propsh Hontichre']]

In [111]:
y =d.iloc[:, -1].values
print(y)

[False  True False ...  True False  True]

In [117]:
y=d['VIP'].values
y

array([False, False, True, ..., False, False, False], dtype=object)

In [131]:
import numpy as np
import pandas as pd
  
# Import dataset
df = pd.read_csv('test.csv')
  
df['HomePlanet'].unique()

array(['Earth', 'Europa', 'Mars', nan], dtype=object)